export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const INITIALIZE_INGREDIENTS = "INITIALIZE_INGREDIENTS";

export const PURCHASE_BURGER_BEGIN = "PURCHASE_BURGER_BEGIN";
export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAILED = "PURCHASE_BURGER_FAILED";

export const INITIALIZE_BURGER = "INITIALIZE_BURGER";

export const AUTH_BEGIN = "AUTH_BEGIN";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
